@startuml
start
:Select patient in XIS

(if needed, launch extension or 
application supporting FHIR / NUTS);
note right
  e.g. a practitioner in EPIC + HINQ
  or a nurse in Zorg bij jou-app
end note

:view patient data from care organisations;
stop
@enduml